# fly.toml app configuration file generated for systemd-test on 2023-06-14T16:11:21+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "systemd-test"
primary_region = "mad"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
